services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.cpu
    container_name: dp_backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    image: node:20
    container_name: dp_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

volumes:
  frontend-node-modules: