FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.cpu.txt .
RUN pip install --no-cache-dir --timeout 1000 --retries 10 -r requirements.cpu.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]